### ISSUE TITLE
My bash post-precessing example does not work any more

### ISSUE THREAD

**Issue by aborruso** [githubocto/flat-postprocessing#6]
Hi,
I have built the bash example you have in this repo readme https://github.com/githubocto/flat-postprocessing#using-bash

I have not made any changes to the bash script and to the `.ts` file for more than 20 days. But the flat action now gives me this error (the [last one](https://github.com/aborruso/flat_data_bash_example/actions/runs/936575958)):

```
  Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
  error: Relative import path "cfb" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
  Error: Error: Command failed: deno run -q -A --unstable ./postprocessing.ts dpc-covid19-ita-regioni-latest.csv
  Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
  error: Relative import path "cfb" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
```

How to solve it?

Thank you

**Comment by irealva** [comment]
HI Andrea can you try using the new version of the flat postprocessing library in your postprocessing script and tell us if it works? 

[https://deno.land/x/flat@0.0.11/mod.ts](https://deno.land/x/flat@0.0.11/mod.ts)

**Comment by irealva** [comment]
Might be because of https://github.com/githubocto/flat/issues/45

**Comment by aborruso** [comment]
> HI Andrea can you try using the new version of the flat library and tell us if it works?

How to use it? Do I must change something in the yml file https://github.com/aborruso/flat_data_bash_example/blob/main/.github/workflows/flat.yml ?

**Comment by irealva** [comment]
Oh I meant here: [https://github.com/aborruso/flat_data_bash_example/blob/main/postprocessing.ts#L1](https://github.com/aborruso/flat_data_bash_example/blob/main/postprocessing.ts#L1)

**Comment by aborruso** [comment]
it works, thank you @irealva
