### ISSUE TITLE
about https://deno.land/x/flat@0.0.x/mod.ts

### ISSUE THREAD

**Issue by MustafaUnluCodes** [githubocto/flat-postprocessing#9]
Hi

I am using  https://deno.land/x/flat@0.0.11/mod.ts in my prostprocess.js file.
it starts to get this error;
"Error: Command failed: NO_COLOR=true deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js btc-price.json
Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
error: TS1192 [ERROR]: Module '"https://jspm.dev/xlsx.js"' has no default export.
import xlsxlib from 'https://jspm.dev/xlsx'
       ~~~~~~~
    at https://deno.land/x/flat@0.0.11/src/xlsx.ts:1:8"

after changing to https://deno.land/x/flat@0.0.14/mod.ts , it is fixed.

but why version 11 starts to get errors. Is it suppose to be backward compatible?

thanks.

**Comment by irealva** [comment]
Sorry about that! It's tied to a problem with the underlying `SheetsJS` library we're using for processing of xlsx files (we hadn't pinned the version we were using). So happened within one of the dependencies we're using ourselves in this post-processing library. 

There's more context in this issue: [https://github.com/githubocto/flat/issues/67](https://github.com/githubocto/flat/issues/67).
